CREATE TABLE IF NOT EXISTS CLIENT (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(128) NOT NULL,
    phone_number VARCHAR(32) NOT NULL,
    cnh VARCHAR(32) NOT NULL,
    rg VARCHAR(32) NOT NULL,
    cpf VARCHAR(32) NOT NULL,
    state VARCHAR(128) NOT NULL,
    city VARCHAR(128) NOT NULL
)